AWSTemplateFormatVersion: "2010-09-09"

Resources:

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cleaned-s3-cleaned-data-1944

  IngestionGlueJob:
    Type: AWS::Glue::Job
    DependsOn:
      # - SourceBucket
      - DestinationBucket
    Properties:
      Name: data-cleaning-1
      Role: arn:aws:iam::062024247186:role/LabRole
      GlueVersion: '2.0'  # Glue version should be set to 2.0 for AWS Glue 2.0
      Timeout: 230
      WorkerType: G.1X
      NumberOfWorkers: 12
      Command:
        Name: glueetl
        ScriptLocation: s3://script-for-glue-3/glue-script.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  # TransformationGlueJob:
  #   Type: AWS::Glue::Job
  #   Properties:
  #     Name: crime-transformation
  #     Role: arn:aws:iam::062024247186:role/LabRole
  #     GlueVersion: 4.0
  #     NumberOfWorkers: 12
  #     Timeout: 30
  #     WorkerType: G.1X
  #     Command:
  #       Name: glueetl
  #       ScriptLocation: s3://inject1w/transform.py
  #     DefaultArguments:
  #       "--job-language": "python"
  #     ExecutionProperty:
  #       MaxConcurrentRuns: 1

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: data-cleaning-workflow

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: gluetriggerimport
      Type: EVENT
      WorkflowName: data-cleaning-workflow

  # GlueTriggerTransform:
    # Type: AWS::Glue::Trigger
    # DependsOn:
    #   - GlueWorkflow
    #   - TransformationGlueJob
    #   - GlueTriggerImport
    # Properties:
    #   Actions:
    #     - JobName: !Ref TransformationGlueJob
    #   Description: Triggers the transformation job
    #   Name: gluetriggertransform
    #   Predicate:
    #     Conditions:
    #       - JobName: !Ref IngestionGlueJob
    #         LogicalOperator: EQUALS
    #         State: SUCCEEDED
    #     Logical: AND
    #   Type: CONDITIONAL
    #   StartOnCreation: True
    #   WorkflowName: crime-workflow

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: database-grp3

  DataCrawler1:
    Type: AWS::Glue::Crawler
    DependsOn:
      # - SourceBucket
      - DestinationBucket
      - GlueDatabase
      - GlueWorkflow
      # - GlueTriggerTransform
    Properties:
      Name: data-crawler-grp3
      DatabaseName: database-grp3 # Replace with your desired Glue database name
      Targets:
        S3Targets:
          - Path: s3://cleaned-s3-cleaned-data-1944 # Specify the path of the bucket you want to crawl
      Role: arn:aws:iam::062024247186:role/LabRole

  # DataCrawler2:
  #   Type: AWS::Glue::Crawler
  #   DependsOn:
  #     - SourceBucket
  #     - DestinationBucket
  #     - GlueDatabase
  #     - GlueWorkflow
  #     - GlueTriggerTransform
  #   Properties:
  #     Name: data-crawler6
  #     DatabaseName: crime6 # Replace with your desired Glue database name
  #     Targets:
  #       S3Targets:
  #         - Path: s3://group-6-datawarehousenew/STREET/ # Specify the path of the bucket you want to crawl
  #     Role: arn:aws:iam::385509221169:role/LabRole

  # GlueTriggerForCrawler1:
  #   Type: AWS::Glue::Trigger
  #   DependsOn:
  #     - GlueTriggerTransform
  #   Properties:
  #     Name: GlueTriggerForCrawler1
  #     Type: CONDITIONAL
  #     Actions:
  #       - CrawlerName: !Ref data-crawler-grp3
  #         NotificationProperty:
  #           NotifyDelayAfter: 1
  #     Predicate:
  #       Conditions:
  #         - JobName: !Ref TransformationGlueJob
  #           LogicalOperator: EQUALS
  #           State: SUCCEEDED
  #       Logical: AND
  #     StartOnCreation: True
  #     WorkflowName: data-cleaning-workflow

  # GlueTriggerForCrawler2:
  #   Type: AWS::Glue::Trigger
  #   DependsOn:
  #     - GlueTriggerTransform
  #   Properties:
  #     Name: GlueTriggerForCrawler2
  #     Type: CONDITIONAL
  #     Actions:
  #       - CrawlerName: !Ref DataCrawler2
  #         NotificationProperty:
  #           NotifyDelayAfter: 1
  #     Predicate:
  #       Conditions:
  #         - JobName: !Ref TransformationGlueJob
  #           LogicalOperator: EQUALS
  #           State: SUCCEEDED
  #       Logical: AND
  #     StartOnCreation: True
  #     WorkflowName: crime-workflow
