

      
AWSTemplateFormatVersion: "2010-09-09"

Resources:
#   DestinationBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: cleaned-s3-cleaned-data-1944

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cleaned-s3-cleaned-data-1944
    BucketPolicy:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal: "*"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::cleaned-s3-cleaned-data-1944/*"
        - Effect: "Allow"
          Principal:
            Service: "glue.amazonaws.com"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::cleaned-s3-cleaned-data-1944/*"



  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: Data_Cleaning1
      Role: arn:aws:iam::062024247186:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 10
      Timeout: 2880
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://script-for-glue-3/glue-job-scrript.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: data-workflow-grp3

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: gluetriggerimport
      Type: EVENT
      WorkflowName: data-workflow-grp3

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: gitdatabase

  DataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - DestinationBucket
      - GlueDatabase
      - GlueWorkflow
    Properties:
      Name: data-crawler6
      DatabaseName: gitdatabase
      Targets:
        S3Targets:
          - Path: s3://cleaned-s3-cleaned-data
      Role: arn:aws:iam::062024247186:role/LabRole


    
