AWSTemplateFormatVersion: "2010-09-09"
#fv
Resources: 


  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: grp-03-simulated-data

  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: ingestion-transformation
      Role: arn:aws:iam::385117466836:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 2
      Timeout: 10
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://part1-glue-script/glue-scrip-3.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: simulated-workflow

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: trigger-glue-import
      Type: EVENT
      WorkflowName: simulated-workflow

  GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: simulated-db

  DataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - DestinationBucket
      - GlueDatabase
      - GlueWorkflow
    Properties:
      Name: data-crawler7
      DatabaseName: simulated-db
      Targets:
        S3Targets:
          - Path: s3://grp-03-simulated-data/ 
      Role: arn:aws:iam::385117466836:role/LabRole


  GlueTriggerForCrawler:
      Type: AWS::Glue::Trigger
      DependsOn:
        - GlueTriggerImport
      Properties:
        Name: GlueTriggerForCrawler
        Type: CONDITIONAL
        Actions:
          - CrawlerName: !Ref DataCrawler
            NotificationProperty:
              NotifyDelayAfter: 1
        Predicate:
          Conditions:
            - JobName: !Ref IngestionGlueJob
              LogicalOperator: EQUALS
              State: SUCCEEDED
          Logical: AND
        Type: CONDITIONAL
        StartOnCreation: True
        WorkflowName: simulated-workflow
  


      
